rm(list=ls())
library(readxl)
library(Hmisc)
library(MASS)
data06 <- read_xlsx("Assignment Data 0 to 6 months.xlsx")
data713<- read_xlsx("Assignment Data 7 to 13 months.xlsx")
data14 <- read_xlsx("Assignment Data 14 plus months.xlsx")
data012 <- read_xlsx("Assignment Data 0 to 12 months.xlsx")
data12p <- read_xlsx("Assignment Data 12 plus months.xlsx")

mydata<-read_excel("ChurnData.xlsx")
lg06<-glm(Churn~CustomerAge+CHIScoreMonth0+CHIScore0to1+SupportCasesMonth0+SupportCases0to1+SPMonth0+SP0to1+Logins0to1+BlogArticles0to1+Views0to1+DaysSinceLastLogin0to1,data=data06,family=binomial(link="logit"))
summary(lg06)
lg713<-glm(Churn~CustomerAge+CHIScoreMonth0+CHIScore0to1+SupportCasesMonth0+SupportCases0to1+SPMonth0+SP0to1+Logins0to1+BlogArticles0to1+Views0to1+DaysSinceLastLogin0to1,data=data713,family=binomial(link="logit"))
summary(lg713)
lg14<-glm(Churn~CustomerAge+CHIScoreMonth0+CHIScore0to1+SupportCasesMonth0+SupportCases0to1+SPMonth0+SP0to1+Logins0to1+BlogArticles0to1+Views0to1+DaysSinceLastLogin0to1,data=data14,family=binomial(link="logit"))
summary(lg14)
lg012<-glm(Churn~CustomerAge+CHIScoreMonth0+CHIScore0to1+SupportCasesMonth0+SupportCases0to1+SPMonth0+SP0to1+Logins0to1+BlogArticles0to1+Views0to1+DaysSinceLastLogin0to1,data=data012,family=binomial(link="logit"))
summary(lg012)
lg12p<-glm(Churn~CustomerAge+CHIScoreMonth0+CHIScore0to1+SupportCasesMonth0+SupportCases0to1+SPMonth0+SP0to1+Logins0to1+BlogArticles0to1+Views0to1+DaysSinceLastLogin0to1,data=data12p,family=binomial(link="logit"))
lg12p<-glm(Churn~CustomerAge+CHIScoreMonth0+CHIScore0to1+SupportCasesMonth0+SupportCases0to1+SPMonth0+SP0to1+Logins0to1+BlogArticles0to1+Views0to1+DaysSinceLastLogin0to1,data=data12p,family=binomial(link="logit"))

summary(lg12p)
confint(lg06)
confint(lg713)
confint(lg14)
install.packages("DAAG")
library(DAAG)
library(lattice)
op <- par(mfrow=c(2,2), mar=.4+c(4,4,1,1), oma= c(0,0,2,0))
cdplot(as.factor(Churn)~CustomerAge,data=data06,main='Density Graph',ylab='churn rate',xlab='Customer Age')
cdplot(as.factor(Churn)~CustomerAge,data=data713,main='Density Graph',ylab='churn rate',xlab='Customer Age')
cdplot(as.factor(Churn)~CustomerAge,data=data14,main='Density Graph',ylab='churn rate',xlab='Customer Age')
cdplot(as.factor(Churn)~CustomerAge,data=mydata,main='Density Graph',ylab='churn rate',xlab='Customer Age')
