rm(list=ls())
library(readxl)
install.packages("Hmisc")
library(Hmisc) 
install.packages("ggthemes")
require(ggplot2)
require(ggthemes)
fiat <- read_excel("fiat.xls")
ford <- read_excel("ford.xls")
opel <- read_excel("opel.xls")
peugeot <- read_excel("peugeot.xls")
renault <- read_excel("renault.xls")
# load the data subset
AW_fiat <- fiat$Awareness
AW_fiat1 <- Lag(AW_fiat,shift=1)
GRP_fiat <- fiat$GRP
LGRP_fiat <- log(1+GRP_fiat)
AW_ford <- ford$Awareness
AW_ford1 <- Lag(AW_ford,shift=1)
GRP_ford <- ford$GRP
LGRP_ford <- log(1+GRP_ford)
AW_opel <- opel$Awareness
AW_opel1 <- Lag(AW_opel,shift=1)
GRP_opel <- opel$GRP
LGRP_opel <- log(1+GRP_opel)
AW_peugeot <- peugeot$Awareness
AW_peugeot1 <- Lag(AW_peugeot,shift=1)
GRP_peugeot <- peugeot$GRP
LGRP_peugeot <- log(1+GRP_peugeot)
AW_renault <- renault$Awareness
AW_renault1 <- Lag(AW_renault,shift=1)
GRP_renault <- renault$GRP
LGRP_renault <- log(1+GRP_renault)
sqrtgrp_fiat<- sqrt(GRP_fiat)
sqrtgrp_ford<- sqrt(GRP_ford)
sqrtgrp_opel<- sqrt(GRP_opel)
sqrtgrp_peugeot<- sqrt(GRP_peugeot)
sqrtgrp_renault<- sqrt(GRP_renault)

##A.REGRESSION for **FIAT**
#1.Regressor: GRP (with intercept)
regA1_fiat<-lm(AW_fiat~GRP_fiat)
summary(regA1_fiat)
AIC(regA1_fiat)
BIC(regA1_fiat)
ggplot(fiat,aes(y=AW_fiat,x=GRP_fiat))+geom_point()+geom_smooth(method=lm,se=FALSE)+
  theme_economist_white()
#2.Regressor: Lagged AW, GRP (with intercept)
regA2_fiat<-lm(AW_fiat~AW_fiat1+GRP_fiat)
summary(regA2_fiat)
regA2_fiat$coefficients
AIC(regA2_fiat)
BIC(regA2_fiat)
#3.Regressor: Lagged AW, GRP (without intercept)
regA3_fiat<-lm(AW_fiat~AW_fiat1+GRP_fiat-1)
summary(regA3_fiat)
AIC(regA3_fiat)
BIC(regA3_fiat)

#4.Regressor: Lagged AW, Log(GRP) (with intercept)
regA4_fiat<-lm(AW_fiat~AW_fiat1+LGRP_fiat)
summary(regA4_fiat)
AIC(regA4_fiat)
BIC(regA4_fiat)

#5.Regressor: Lagged AW, sqrt(GRP)
regA5_fiat<-lm(AW_fiat~AW_fiat1+sqrtgrp_fiat)
summary(regA5_fiat)
AIC(regA5_fiat)
BIC(regA5_fiat)

##B.REGRESSION for **FORD**
#1.Regressor: GRP (with intercept)
regB1_ford<-lm(AW_ford~GRP_ford)
summary(regB1_ford)
AIC(regB1_ford)
BIC(regB1_ford)
ggplot(ford,aes(y=AW_ford,x=GRP_ford))+geom_point()+geom_smooth(method=lm,se=FALSE)+
  theme_economist_white()
#2.Regressor: Lagged AW, GRP (with intercept)
regB2_ford<-lm(AW_ford~AW_ford1+GRP_ford)
summary(regB2_ford)
AIC(regB2_ford)
BIC(regB2_ford)
#3.Regressor: Lagged AW, GRP (without intercept)
regB3_ford<-lm(AW_ford~AW_ford1+GRP_ford-1)
summary(regB3_ford)
AIC(regB3_ford)
BIC(regB3_ford)

#4.Regressor: Lagged AW, Log(GRP) (with intercept)
regB4_ford<-lm(AW_ford~AW_ford1+LGRP_ford)
summary(regB4_ford)
AIC(regB4_ford)
BIC(regB4_ford)

#5.Regressor: Lagged AW, sqrt(GRP)
regB5_ford<-lm(AW_ford~AW_ford1+sqrtgrp_ford)
summary(regB5_ford)
AIC(regB5_ford)
BIC(regB5_ford)

##C.REGRESSION for **OPEL**
#1.Regressor: GRP (with intercept)
regC1_opel<-lm(AW_opel~GRP_opel)
summary(regC1_opel)
AIC(regC1_opel)
BIC(regC1_opel)
ggplot(opel,aes(y=AW_opel,x=GRP_opel))+geom_point()+geom_smooth(method=lm,se=FALSE)+
  theme_dark()
#2.Regressor: Lagged AW, GRP (with intercept)
regC2_opel<-lm(AW_opel~AW_opel1+GRP_opel)
summary(regC2_opel)
AIC(regC2_opel)
BIC(regC2_opel)
#3.Regressor: Lagged AW, GRP (without intercept)
regC3_opel<-lm(AW_opel~AW_opel1+GRP_opel-1)
summary(regC3_opel)
AIC(regC3_opel)
BIC(regC3_opel)

#4.Regressor: Lagged AW, Log(GRP) (with intercept)
regC4_opel<-lm(AW_opel~AW_opel1+LGRP_opel)
summary(regC4_opel)
AIC(regC4_opel)
BIC(regC4_opel)

#5.Regressor: Lagged AW, sqrt(GRP)
regC5_opel<-lm(AW_opel~AW_opel1+sqrtgrp_opel)
summary(regC5_opel)
AIC(regC5_opel)
BIC(regC5_opel)

##D.REGRESSION for **PEUGEOT**
#1.Regressor: GRP (with intercept)
regD1_peugeot<-lm(AW_peugeot~GRP_peugeot)
summary(regD1_peugeot)
AIC(regD1_peugeot)
BIC(regD1_peugeot)
ggplot(peugeot,aes(y=AW_peugeot,x=GRP_peugeot))+geom_point()+geom_smooth(method=lm,se=FALSE)+
  theme_economist_white()
#2.Regressor: Lagged AW, GRP (with intercept)
regD2_peugeot<-lm(AW_peugeot~AW_peugeot1+GRP_peugeot)
summary(regD2_peugeot)
AIC(regD2_peugeot)
BIC(regD2_peugeot)
#3.Regressor: Lagged AW, GRP (without intercept)
regD3_peugeot<-lm(AW_peugeot~AW_peugeot1+GRP_peugeot-1)
summary(regD3_peugeot)
AIC(regD3_peugeot)
BIC(regD3_peugeot)

#4.Regressor: Lagged AW, Log(GRP) (with intercept)
regD4_peugeot<-lm(AW_peugeot~AW_peugeot1+LGRP_peugeot)
summary(regD4_peugeot)
AIC(regD4_peugeot)
BIC(regD4_peugeot)

#5.Regressor: Lagged AW, sqrt(GRP)
regD5_peugeot<-lm(AW_peugeot~AW_peugeot1+sqrtgrp_peugeot)
summary(regD5_peugeot)
AIC(regD5_peugeot)
BIC(regD5_peugeot)

##E.REGRESSION for **RENAULT**
#1.Regressor: GRP (with intercept)
regE1_renault<-lm(AW_renault~GRP_renault)
summary(regE1_renault)
AIC(regE1_renault)
BIC(regE1_renault)
ggplot(renault,aes(y=AW_renault,x=GRP_renault))+geom_point()+geom_smooth(method=lm,se=FALSE)+
  theme_economist_white()
#2.Regressor: Lagged AW, GRP (with intercept)
regE2_renault<-lm(AW_renault~AW_renault1+GRP_renault)
summary(regE2_renault)
AIC(regE2_renault)
BIC(regE2_renault)
#3.Regressor: Lagged AW, GRP (without intercept)
regE3_renault<-lm(AW_renault~AW_renault1+GRP_renault-1)
summary(regE3_renault)
AIC(regE3_renault)
BIC(regE3_renault)

#4.Regressor: Lagged AW, Log(GRP) (with intercept)
regE4_renault<-lm(AW_renault~AW_renault1+LGRP_renault)
summary(regE4_renault)
AIC(regE4_renault)
BIC(regE4_renault)

#5.Regressor: Lagged AW, sqrt(GRP)
regE5_renault<-lm(AW_renault~AW_renault1+sqrtgrp_renault)
summary(regE5_renault)
AIC(regE5_renault)
BIC(regE5_renault)


#***AD ELASTICITY
A3 <- data.frame(regA3_fiat[1])
B3 <- data.frame(regB3_ford[1])
C3 <- data.frame(regC3_opel[1])
D3 <- data.frame(regD3_peugeot[1])
E3 <- data.frame(regE3_renault[1])
mean_fiat_a <- mean(fiat$Awareness)
mean_ford_a <- mean(ford$Awareness)
mean_opel_a <- mean(opel$Awareness)
mean_peugeot_a <- mean(peugeot$Awareness)
mean_renault_a <- mean(renault$Awareness)
(Ad_Elaaticity_A3 <- A3[2,1]/((1-A3[1,1])*mean_fiat_a))
(Ad_Elaaticity_B3 <- B3[2,1]/((1-B3[1,1])*mean_ford_a))
(Ad_Elaaticity_C3 <- C3[2,1]/((1-C3[1,1])*mean_opel_a))
(Ad_Elaaticity_D3 <- D3[2,1]/((1-D3[1,1])*mean_peugeot_a))
(Ad_Elaaticity_E3 <- E3[2,1]/((1-E3[1,1])*mean_renault_a))

A4 <- data.frame(regA4_fiat[1])
B4 <- data.frame(regB4_ford[1])
C4 <- data.frame(regC4_opel[1])
D4 <- data.frame(regD4_peugeot[1])
E4 <- data.frame(regE4_renault[1])
mean_fiat_a <- mean(fiat$Awareness)
mean_ford_a <- mean(ford$Awareness)
mean_opel_a <- mean(opel$Awareness)
mean_peugeot_a <- mean(peugeot$Awareness)
mean_renault_a <- mean(renault$Awareness)
(Ad_Elaaticity_A4 <- A4[2,1]/((1-A4[1,1])*mean_fiat_a))
(Ad_Elaaticity_B4 <- B4[2,1]/((1-B4[1,1])*mean_ford_a))
(Ad_Elaaticity_C4 <- C4[2,1]/((1-C4[1,1])*mean_opel_a))
(Ad_Elaaticity_D4 <- D4[2,1]/((1-D4[1,1])*mean_peugeot_a))
(Ad_Elaaticity_E4 <- E4[2,1]/((1-E4[1,1])*mean_renault_a))